### ISSUE TITLE
BrunchError: Failed to read file node_modules/node_modules/hogan.js/web/builds/2.0.0/template-2.0.0.js.

### ISSUE THREAD

**Issue by mikebaldry** [mdp/hoganjs-brunch#7]
```
(node:68345) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): BrunchError: Failed to read file node_modules/node_modules/hogan.js/web/builds/2.0.0/template-2.0.0.js.
Error: ENOENT: no such file or directory, open '/Users/mikeyb/projects/web/node_modules/node_modules/hogan.js/web/builds/2.0.0/template-2.0.0.js'
```

Curiously removing the include fixes this, as does removing the `node_modules` path in the include property.

**Comment by leegee** [comment]
Same thing on Win10 on initial install of this module via my (first) brunch project's package.json.

**Comment by designermonkey** [comment]
The issue is [here](https://github.com/mdp/hoganjs-brunch/blob/master/index.js#L33). No need for `node_modules` path item.
